in:
  type: google_spreadsheets
  auth_method: service_account
  json_keyfile: service_account.json
  spreadsheets_url: https://docs.google.com/spreadsheets/d/1EvMJBRvsphQXxEisC52xKcFgqtnQ7C4vlo9GQzlZRQ4/edit?gid=0#gid=0
  worksheet_title: tables
  start_row: 2
  default_timezone: 'Asia/Tokyo'
  null_string: '\N'
  default_typecast: strict
  columns:
    - {name: project, type: long}
    - {name: dataset, type: string}
    - {name: table, type: string}
    - {name: column, type: string}
out:
  type: bigquery
  mode: append
  auth_method: service_account
  json_keyfile: service_account.json
  project: linear-enigma-289302
  dataset: digdag
  table: tables
  source_format: CSV