services:
  digdag:
    container_name: digdag
    build: ./digdag
    tty: true
    ports:
      - "65433:65433"
      - "65434:65434"
    volumes:
      - ./digdag/service_account.json:/app/service_account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json